cache: bundler
language: ruby
rvm: 2.2.3
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
script:
- bundle exec rspec
- bundle exec rubocop
addons:
  postgresql: '9.4'
  code_climate:
    repo_token: b83ed7a245c8d4bf3019834f0efb9ffca11c9fc64ec99c3f6d7d038a9e5a5a15
deploy:
  provider: heroku
  run: rake db:migrate
  api_key:
    secure: rTlNNb3nrgpmfDdibCJJyJkCKzNi5Ug/FxoLLWhtSXJ/guurNx9N6Wd0kgp/7nje6NNIPcxCTsp3VpyqibtmIrNWz+0vNEVu534SY1T8Tx9IBAKRENLLDF8iT0Yv97U44uS2qkTX/OrB+Sy/BaL+jckAEHrPocsQxIV2p5qmRayzKhlxXl3cjrQW1TH775V3a+u4M18gcEc3RBUPstuMAvrWeVO0PBUOE5qZbsJvR1vNg5GDr8engezxEbqw+yJ8x6CKG6Cn90ZR4pb96Vq77EsMXvbt5++ZEsL4qT4IzQFJXrrO43iA6JaoVV/Weh99RcWl13Bi51wo8pphwzO7YCNJWU366ESKII8gMXlff1a1WHH/IhfHNSfB/r7lSmy7NQl3XT+PB4GfXwklIKc5knRLyuv3scB9oUBXJylhHbg6irFm/g8rMY4dD9x/jJLVmbByjpASgONfS2XjPL/QU3WQJVYZic+aLapU5ykI8s/MjB35mhWN0BMANNfH+H8ikDTzDYagcq0ZLL/W/TSIQNLOsTuJvlaMUzVGMetj3n8BYV4kHKnugWCfbNzfCioCemma8oNEoksWJkR/nmUYlev+EkfBNVwBctsQm0DCUxNq7o0IUU7+06TabrkWPVo9ZbaJeLXmxC4aBlew2PeiFag7JLgRSeSRbOnsFg4RGmE=
  app: afternoon-thicket-17904
  on:
    repo: putaring/furry-octo-memory
    branch: master
