cache: bundler
language: ruby
rvm: 2.2.3
script:
- bin/rails db:migrate RAILS_ENV=test
- bundle exec rspec
- bundle exec rubocop
addons:
  code_climate:
    repo_token: f17460fe606b39aa24f434406f831a8b10e383b741c3e57d049327591131d836
