cache: bundler
language: ruby
rvm: 2.2.0
script:
- bin/rails db:migrate RAILS_ENV=test
- bundle exec rspec
- bundle exec rubocop
addons:
  code_climate:
    repo_token: f17460fe606b39aa24f434406f831a8b10e383b741c3e57d049327591131d836
deploy:
  provider: heroku
  api_key:
    secure: ME/7+7NfBtpEn9s7t6RKcUD39/ww13aWxBWH4W/egzqz4DgvYKM+ceSDzoy3QCGopDCEYeAe2UGuBanggLspRebp8S70+GgMPGVelAK2xIJn3hkfQn+zIP9yOX6LgDePsHPc1A8kSPo16jH4QlAKFaBvdpyNWH4UtVziSWuvD2fRJ6ql5xnWTkzHIlRDO5nVtRTwi0U8W7HwRiyHeMQT9IYTCaJa59vkNysTCbrCJB6s/j9GVxwD820CtiNSThTTVe2dE3lRhSdVBtq5XaOmhUGfh/Skhti4I3q27KqdxpWN6FOJtDQnPg8TXgIIUC66GHY3Os7I10QCdft/rZsblXRtjMl1CvBjApKFnJ1JQo8/6MQZEGKqwEVJkYeZScoDIrd5KUuenOhdLBqmi+dx4NmGeYG3LhUlbP7oAd6XaUbVbWonqTu3Sx8USeREsTBgPRnonywkz1UKVHGqNNFGyS2LL5MaGlo49QoRkNr2nWQI+h4uJjOd/ZGFXv9NIwk3SMIxx5BdDWBfaI1D5312/Rw92pRYF+Wub3JBmXIoTgzwLfI+CdP7PPtr6qm4+ai9fz2pMLXygjY7ZU+fMaJtCjseG09Q3Sv+QU+CzpWLVB9sKOSBASBnw6GKLccNaDXKxYDU8BzCTumLL0BxbfvIcTHPW4XwM1ZWWd5S/ElCijc=
  app: afternoon-thicket-17904
  on:
    repo: sanjaykamaruddin/joonam
